name: Deploy Lakehouse Pipeline to AWS

on:
  push:
    branches:
      - main
    paths:
      - "scripts/**"
      - "state_machine/**"
      - "pre_validation_lambda/**"
      - "template.yaml"

env:
  S3_BUCKET_NAME: lab5-ecommerce-lakehouse
  AWS_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Set up SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GitHubActionsDeploy

      # - name: Lint Python Scripts
      #   run: |
      #     pip install pylint
      #     pylint scripts/*.py
      #     pylint pre_validation_lambda/*.py

      - name: Build SAM Application
        run: sam build --use-container

      - name: Deploy Serverless Application (Lambda, Role, Trigger)
        run: |
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset \
            --stack-name e-commerce-lakehouse-resources \
            --s3-bucket ${{ env.S3_BUCKET_NAME }} \
            --s3-prefix "sam-deploys" \
            --capabilities CAPABILITY_IAM \
            --parameter-overrides StateMachineArn=${{ vars.STATE_MACHINE_ARN }}

      - name: Deploy Glue Scripts to S3
        run: |
          aws s3 sync ./scripts/ s3://${{ env.S3_BUCKET_NAME }}/scripts/ --delete

      - name: Deploy Step Functions State Machine
        run: |
          aws stepfunctions update-state-machine \
            --state-machine-arn ${{ vars.STATE_MACHINE_ARN }} \
            --definition "file://state_machine/ecommerce-pipeline.asl.json"
