name: Deploy Lakehouse Pipeline to AWS

on:
  push:
    branches:
      - main

    paths:
      - "scripts/**"
      - "state_machine/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
          role-session-name: GitHubActionsDeploy

      - name: Check S3 bucket existence
        run: |
          echo "Checking if S3 bucket exists..."
          aws s3 ls s3://${{ vars.S3_BUCKET_NAME }} || { echo "Bucket does not exist"; exit 1; }

      - name: Validate State Machine Definition
        run: |
          echo "Installing asl-validator..."
          pip install asl-validator
          echo "Validating State Machine definition..."
          asl-validator state_machine/ecommerce-pipeline.asl.json || { echo "Invalid ASL definition"; exit 1; }

      - name: Deploy scripts to S3
        run: |
          echo "Syncing ETL scripts to S3 bucket s3://${{ vars.S3_BUCKET_NAME }}/scripts/..."
          aws s3 sync ./scripts/ s3://${{ vars.S3_BUCKET_NAME }}/scripts/ --delete
          # Note: --delete removes files in S3 not present locally

      - name: "Deploy Step Functions State Machine"
        run: |
          echo "Updating State Machine definition..."
          aws stepfunctions update-state-machine --state-machine-arn ${{ vars.STATE_MACHINE_ARN }} --definition "$(cat state_machine/ecommerce-pipeline.asl.json)"
